/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elio Flores
 */
public class Registro extends javax.swing.JInternalFrame {

  private List<Contacto> contactos;
  private Contacto contactoActual;

  /**
   * Creates new form Registro
   */
  public Registro(List<Contacto> contactos) {
    this.contactos = contactos;
    this.contactoActual = new Contacto();
    initComponents();
    initTabla();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    id = new javax.swing.JTextField();
    nombre = new javax.swing.JTextField();
    telefono = new javax.swing.JTextField();
    mail = new javax.swing.JTextField();
    nuevo = new javax.swing.JButton();
    guardar = new javax.swing.JButton();
    eliminar = new javax.swing.JButton();
    cancelar = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTable();
    buscar = new javax.swing.JButton();

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane2.setViewportView(jTable2);

    setClosable(true);

    jLabel1.setText("Id");

    jLabel2.setText("Nombre");

    jLabel3.setText("Telefono");

    jLabel4.setText("Mail");

    nuevo.setText("Nuevo");
    nuevo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nuevoActionPerformed(evt);
      }
    });

    guardar.setText("Guardar");
    guardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guardarActionPerformed(evt);
      }
    });

    eliminar.setText("Eliminar");
    eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eliminarActionPerformed(evt);
      }
    });

    cancelar.setText("Cancela");
    cancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelarActionPerformed(evt);
      }
    });

    tabla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane3.setViewportView(tabla);

    buscar.setText("Buscar");
    buscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buscarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel4)
              .addComponent(jLabel3)
              .addComponent(jLabel2)
              .addComponent(nuevo))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(guardar)
                .addGap(39, 39, 39)
                .addComponent(eliminar)
                .addGap(31, 31, 31)
                .addComponent(cancelar))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(nombre))
                  .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1))
            .addContainerGap(24, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buscar))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)))
        .addGap(39, 39, 39)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nuevo)
          .addComponent(guardar)
          .addComponent(eliminar)
          .addComponent(cancelar))
        .addGap(31, 31, 31)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
    // TODO add your handling code here:
    id.setText("");
    nombre.setText("");
    telefono.setText("");
    mail.setText("");

    contactoActual = new Contacto();
  }//GEN-LAST:event_cancelarActionPerformed

  private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    // TODO add your handling code here:
    contactoActual = new Contacto();

    contactoActual.setNombre(nombre.getText());
    contactoActual.setTelefono(telefono.getText());
    contactoActual.setEmail(mail.getText());
    contactoActual.setId(Integer.parseInt(id.getText()));

    contactos.add(contactoActual);

    actualizarTabla();

  }//GEN-LAST:event_nuevoActionPerformed

  private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    // TODO add your handling code here:
    contactoActual.setId(Integer.parseInt(id.getText()));
    contactoActual.setNombre(nombre.getText());
    contactoActual.setTelefono(telefono.getText());
    contactoActual.setEmail(mail.getText());

    actualizarTabla();
  }//GEN-LAST:event_guardarActionPerformed

  private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
    // TODO add your handling code here:
    int contactoId = Integer.parseInt(id.getText());

    for (Contacto contacto : contactos) {
      if (contacto.getId() == contactoId) {
        contactoActual = contacto;
        break;
      }
    }

    mostrarContactoActual();
  }//GEN-LAST:event_buscarActionPerformed

  private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
    // TODO add your handling code here:
    contactos.remove(contactoActual);
    actualizarTabla();
  }//GEN-LAST:event_eliminarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buscar;
  private javax.swing.JButton cancelar;
  private javax.swing.JButton eliminar;
  private javax.swing.JButton guardar;
  private javax.swing.JTextField id;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTable jTable1;
  private javax.swing.JTable jTable2;
  private javax.swing.JTextField mail;
  private javax.swing.JTextField nombre;
  private javax.swing.JButton nuevo;
  private javax.swing.JTable tabla;
  private javax.swing.JTextField telefono;
  // End of variables declaration//GEN-END:variables

  private void actualizarTabla() {
    DefaultTableModel modelo = ((DefaultTableModel) tabla.getModel());
    vaciarTabla();
    for (Contacto contacto : contactos) {
      modelo.addRow(new Object[]{contacto.getId(),
        contacto.getNombre(),
        contacto.getTelefono(),
        contacto.getEmail()
      });
    }
  }

  private void vaciarTabla() {
    DefaultTableModel modelo = ((DefaultTableModel) tabla.getModel());
    for (int fila = tabla.getRowCount() - 1; fila >= 0; fila--) {
      modelo.removeRow(fila);
    }
  }

  private void initTabla() {
    DefaultTableModel modelo = new DefaultTableModel() {
      public boolean isCellEditable(int f, int c) {
        return false;
      }
    };
    modelo.addColumn("Id");
    modelo.addColumn("Nombre");
    modelo.addColumn("Telefono");
    modelo.addColumn("Email");
    tabla.setModel(modelo);
  }

  private void mostrarContactoActual() {
    nombre.setText(contactoActual.getNombre());
    telefono.setText(contactoActual.getTelefono());
    mail.setText(contactoActual.getEmail());
    id.setText(contactoActual.getId() + "");
  }
}
